### ISSUE TITLE
Question: what is the purpose of unwrapping 3d models?

### ISSUE THREAD

**Issue by dkrikun** [Arahnoid/UVChecker-map#2]
Hello,

Sorry for ignorance, could you please explain what is the purpose of unwrapping 3d models, and why someone would want to do it and to use these textures?

Thanks!

**Comment by Arahnoid** [comment]
## What is Unwrapping?

In short the Unwrapping is used to generate texture coordinates.
Imagine you have a head object it is a 3D object (it have width height and depth XYZ coordinates) and you want to paint a texture for it.

 The problem is what textures are 2D images what have just height and width XY coordinates. In order to apply 2D image to 3D object you must unfold 3D object (kind of convert it to 2D). 
Basically this is a unwrapping

![example](http://www.blender.org/wp-content/uploads/2012/11/UV-Unwrapping2.png)

Bad UV on the torso ( not uniform, UV Space is out of 0,1 space)
![](http://create.bluemars.com/wiki/images/6/62/Cloth_UVLayoutBad.jpg)

Good UV(uniform, well aranged)
![](http://create.bluemars.com/wiki/images/f/fd/Cloth_UVLayoutGood.jpg)

When you unwrap a model you get into some issues like how stretched are you UV coordinates how much space them use, position, rotation and in some cases you may get flipped results so to understand how you UV works will help textures provided in this repo :)

[https://www.youtube.com/watch?v=-kfqLxlCTl4](https://www.youtube.com/watch?v=-kfqLxlCTl4)
[https://www.youtube.com/watch?v=9j47MS5arg0](https://www.youtube.com/watch?v=9j47MS5arg0)

## Why someone would want to use these textures?

As you can see in examples above are used two color checker maps and it is absolutely fine when you have simple model to unwrap you can clearly see how uniform are uv coordinates stretching and so on.
However with using checker images from this repository you will have more advantages and you will be able to get answer to (especially with more complex models):
- where exactly are placed UV islands in UV space
- in which direction are rotated UV
- are the UV flipped 
- how much stretching is applied to (extremely visible with UVCheckerMap16)

This are the answers in short. Hope it helps :)

**Comment by dkrikun** [comment]
Wow! Thanks for such a detailed answer!
I think you could add it (or link from) README.md to attract more people. Good luck :smile:
